### ISSUE TITLE
How to get an icon

### ISSUE THREAD

**Issue by ghost** [watertastesgood/tray-icons#1]
Hey there! Lovely script, I've tried it on a project and it works just fine, except for the icon, I have put an icon file on the project's folder and renamed the char constant on trayicon.h accordingly but for some reason I cannot get it to show up, what can I do?

Thanks!

**Comment by watertastesgood** [comment]
Hey! I'm happy that you've found a use for this. :)

Just tested this on my end and it seems to be working fine. Make sure the .ico file is located in the same folder as the compiled executable, or the root of the project folder if you're just testing through the local windows debugger on visual studio. 

The project was just intended to simplify a majority of the aspects of actually setting the icon or creating menus from tray icons a much easier process. If you want to change the location that the icon is found or bundle it with the program, you'll have to implement this yourself.
